# Generated by Django 5.1.5 on 2025-02-28 17:03

import utils.path_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='О пользователе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default.jpg', null=True, upload_to=utils.path_helpers.profile_avatar_path, verbose_name='Аватар'),
        ),
    ]
