services:
  web:
    build:
      context: .
    container_name: python_dm
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - /app/static
    env_file:
      - .env
    command: >
      poetry run uvicorn core.asgi:application --host 0.0.0.0 --port 8000
    develop:
      watch:
        - path: ./
          target: /app/
          action: sync+restart
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    depends_on:
      - md_pro_db
    networks:
      - backend

  md_pro_db:
    image: postgres:16
    container_name: md_pro_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
