# Generated by Django 5.1.5 on 2025-03-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
    ]
