# Generated by Django 5.1.5 on 2025-02-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='object_id',
            field=models.UUIDField(verbose_name='Идентификатор объекта'),
        ),
    ]
