# Generated by Django 5.1.5 on 2025-03-04 06:11

# import markdownx.models
from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=TextField(verbose_name='Содержание'),
        ),
    ]
